services:
  order-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        SERVICE: order-service
    container_name: saga-order-service
    environment:
      PORT: "8081"
      APPROACH: "${APPROACH:-choreography}"
      FAIL_AT_STEP: "${FAIL_AT_STEP:-}"
      FAIL_AT_ATTEMPT: "${FAIL_AT_ATTEMPT:-0}"
      DELAY_MS: "${DELAY_MS:-0}"
      FAIL_ON_COMPENSATE: "${FAIL_ON_COMPENSATE:-false}"
      DROP_EVENT: "${DROP_EVENT:-}"
      DROP_RESPONSE_AT_STEP: "${DROP_RESPONSE_AT_STEP:-}"
    ports:
      - "8081:8081"
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - saga-infra

  payment-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        SERVICE: payment-service
    container_name: saga-payment-service
    environment:
      PORT: "8082"
      APPROACH: "${APPROACH:-choreography}"
      FAIL_AT_STEP: "${FAIL_AT_STEP:-}"
      FAIL_AT_ATTEMPT: "${FAIL_AT_ATTEMPT:-0}"
      DELAY_MS: "${DELAY_MS:-0}"
      FAIL_ON_COMPENSATE: "${FAIL_ON_COMPENSATE:-false}"
      DROP_EVENT: "${DROP_EVENT:-}"
      DROP_RESPONSE_AT_STEP: "${DROP_RESPONSE_AT_STEP:-}"
    ports:
      - "8082:8082"
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - saga-infra

  inventory-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        SERVICE: inventory-service
    container_name: saga-inventory-service
    environment:
      PORT: "8083"
      APPROACH: "${APPROACH:-choreography}"
      FAIL_AT_STEP: "${FAIL_AT_STEP:-}"
      FAIL_AT_ATTEMPT: "${FAIL_AT_ATTEMPT:-0}"
      DELAY_MS: "${DELAY_MS:-0}"
      FAIL_ON_COMPENSATE: "${FAIL_ON_COMPENSATE:-false}"
      DROP_EVENT: "${DROP_EVENT:-}"
      DROP_RESPONSE_AT_STEP: "${DROP_RESPONSE_AT_STEP:-}"
    ports:
      - "8083:8083"
    depends_on:
      inventory-db:
        condition: service_healthy
    networks:
      - saga-infra

  shipping-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        SERVICE: shipping-service
    container_name: saga-shipping-service
    environment:
      PORT: "8084"
      APPROACH: "${APPROACH:-choreography}"
      FAIL_AT_STEP: "${FAIL_AT_STEP:-}"
      FAIL_AT_ATTEMPT: "${FAIL_AT_ATTEMPT:-0}"
      DELAY_MS: "${DELAY_MS:-0}"
      FAIL_ON_COMPENSATE: "${FAIL_ON_COMPENSATE:-false}"
      DROP_EVENT: "${DROP_EVENT:-}"
      DROP_RESPONSE_AT_STEP: "${DROP_RESPONSE_AT_STEP:-}"
    ports:
      - "8084:8084"
    depends_on:
      shipping-db:
        condition: service_healthy
    networks:
      - saga-infra

  orchestrator:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        SERVICE: orchestrator
    container_name: saga-orchestrator
    environment:
      PORT: "8080"
      SELECTIVE_COMPENSATE: "${SELECTIVE_COMPENSATE:-false}"
    ports:
      - "8080:8080"
    networks:
      - saga-infra


